name: 'Build Devenv'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-devenv:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Use Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-conf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build devenv
        run: nix develop --impure --accept-flake-config
      - name: Check version
        run: nix develop --impure --accept-flake-config --command devenv "version"
