name: Enable automerge on flake update PRs

on:
  # See note below about using pull_request_target
  pull_request_target:
    types: ['labeled', 'opened', 'reopened']

jobs:
  automerge:
    name: Enable automerge on flake update PRs
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'automated') || contains( github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Enable automerge on flake update PRs
        run: gh pr merge --merge --auto "$PR_NUMBER" --repo "$OWNER/$REPO"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
