name: Enable automerge on flake update PRs

on:
  # See note below about using pull_request_target
  pull_request_target:
    types: ['labeled', 'opened', 'reopened']

jobs:
  automerge:
    name: Enable automerge on flake update PRs
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'automated') || contains( github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Enable automerge on flake update PRs
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          github-token: ${{ secrets.PAT }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: 'luqmanishere'

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE
