name: Enable automerge on flake update PRs

on:
  # See note below about using pull_request_target
  pull_request_target:
    types: ['labeled', 'opened', 'reopened']

jobs:
  automerge:
    name: Enable automerge on flake update PRs
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'automated') || contains( github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Enable automerge on flake update PRs
        run: gh pr merge --merge --auto ${{ github.event.pull_request.number }} --repo ${{ github.event.repository.name }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
