name: 'Build Hosts'
on:
  push:
  pull-request:

jobs:
  asuna:
    runs-on: ubuntu-latest
    environment: systemconfig
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: nix-conf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.$GITHUB_JOB.config.system.build.toplevel
    - run: echo "host $GITHUB_JOB OK"

  sinon:
    runs-on: ubuntu-latest
    environment: systemconfig
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: nix-conf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.$GITHUB_JOB.config.system.build.toplevel
    - run: echo "host $GITHUB_JOB OK"
