name: 'Build Systems'
on:
  push:
    branches-ignore:
      - update_flake_lock_action
  pull_request:

jobs:
  build-linux-systems:
    runs-on: ubuntu-latest
    environment: systemconfig
    strategy:
      matrix:
        system: [asuna, sinon]
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v3
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Use Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-conf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build system ${{ matrix.system }}
        run: nix build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel --accept-flake-config
      - run: echo "Build for host ${{ matrix.system }} OK"
